# Generated by Django 5.0.6 on 2024-05-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCarApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='client',
            new_name='user',
        ),
    ]
