# Generated by Django 5.0.6 on 2024-05-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCarApp', '0002_rename_client_auto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='user',
            new_name='users',
        ),
    ]
