# Generated by Django 5.0.6 on 2024-05-13 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCarApp', '0004_review_rating_alter_parkingspot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.PositiveIntegerField(max_length=3, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
