# Generated by Django 5.0.6 on 2024-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCarApp', '0011_alter_parkingspot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='is_parked',
            field=models.BooleanField(default=False),
        ),
    ]
