# Generated by Django 5.0.6 on 2024-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCarApp', '0012_auto_is_parked'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='is_parked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
