# Generated by Django 5.0.6 on 2024-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCarApp', '0013_auto_is_parked_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='is_parked_time',
        ),
        migrations.AlterField(
            model_name='bill',
            name='last_time_payed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
