# Generated by Django 5.0.6 on 2024-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCarApp', '0014_remove_auto_is_parked_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
